run_test – bspline-fortran
run_test Subroutine
62 statements
Source File
subroutine run_test(n)
run test for n x n x n data set
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
Calls
Called by
Contents
Source Code
run_test
Source Code
    subroutine run_test(n)  !! run test for n x n x n data set
    implicit none
    integer,intent(in) :: n
    integer,parameter :: kx = 4    !order
    integer,parameter :: ky = 4
    integer,parameter :: kz = 4
    real(wp),parameter :: tol = 1.0e-14_wp
    type(bspline_3d) :: s3
    integer :: nx,ny,nz
    real(wp),allocatable :: x(:),y(:),z(:)
    real(wp),allocatable  :: fcn_3d(:,:,:)
    real(wp) :: val,tru,err,errmax
    logical  :: fail
    integer  :: i,j,k,l,m,idx,idy,idz
    integer  :: iflag
    nx = n; ny = n; nz = n
    idx = 0; idy = 0; idz = 0
    fail = .false.
    allocate(x(nx))
    allocate(y(ny))
    allocate(z(nz))
    allocate(fcn_3d(nx,ny,nz))
     do concurrent (i=1:nx)
        x(i) = dble(i-1)/dble(nx-1)
     end do
     do concurrent (j=1:ny)
        y(j) = dble(j-1)/dble(ny-1)
     end do
     do concurrent (k=1:nz)
        z(k) = dble(k-1)/dble(nz-1)
     end do
     do i=1,nx
        do j=1,ny
           do k=1,nz
              fcn_3d(i,j,k) = f3(x(i),y(j),z(k))
           end do
        end do
     end do
     !initialize:
     call s3%initialize(x,y,z,fcn_3d,kx,ky,kz,iflag)
     ! free up memory (don't need anymore):
     deallocate(fcn_3d)
     if (iflag/=0) then
         write(*,*) 'Error initializing spline: '//get_status_message(iflag)
         error stop
     end if
    ! compute max error at interpolation points
     errmax = 0.0_wp
     do i=1,nx
        do j=1,ny
           do k=1,nz
                call s3%evaluate(x(i),y(j),z(k),idx,idy,idz,val,iflag)
                tru    = f3(x(i),y(j),z(k))
                err    = abs(tru-val)
                errmax = max(err,errmax)
           end do
        end do
     end do
    ! check max error against tolerance
    write(*,'(I10,1X,I20,1X,E30.16)') n, s3%size_of()*8, errmax    ! n, size, error
    if (errmax >= tol) error stop  ' ** test failed ** '
    end subroutine run_test
Call graph
run_test calls get_status_message, f3
bspline_stack_size_oo_test calls run_test